INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   759
        Validation size: 84
        Checkpoints:     True
        Device:          cpu
        Images scaling:  0.5
        Mixed Precision: False
Epoch 1/5:   0%|                                                                                                    | 0/759 [00:00<?, ?img/s]D:\Python37\lib\site-packages\torch\autocast_mode.py:162: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')




















Epoch 1/5:   3%|█▉                                                                      | 21/759 [01:39<58:12,  4.73s/img, loss (batch)=5.87]
Traceback (most recent call last):
  File "D:\Python37\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "D:\Python37\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "D:\Python37\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 管道正在被关闭。
INFO: Saved interrupt